graph TD
    Ф1["<b>Ф1</b><br/>Аппаратное<br/>обеспечение<br/>исправно"]
    Ф2["<b>Ф2</b><br/>Загрузочный<br/>код<br/>присутствует"]
    
    П1["<b>П1</b><br/>Ф1 ∧ Ф2"]
    Д1["<b>Д1</b><br/>Инициализация<br/>системы"]
    
    Ф3["<b>Ф3</b><br/>Ядро ОС<br/>загружено"]
    П2["<b>П2</b><br/>Д1 ∧ Ф3"]
    Д2["<b>Д2</b><br/>Загрузка<br/>ядра ОС"]
    
    Ф4["<b>Ф4</b><br/>Системные<br/>процессы<br/>инициализированы"]
    П3["<b>П3</b><br/>Д2 ∧ Ф4"]
    Д3["<b>Д3</b><br/>Инициализация<br/>процессов"]
    
    Ф6["<b>Ф6</b><br/>Память<br/>разделена<br/>на разделы"]
    П4["<b>П4</b><br/>Д2 ∧ Ф6"]
    Д4["<b>Д4</b><br/>Управление<br/>памятью"]
    
    Ф7["<b>Ф7</b><br/>ФС<br/>примонтирована"]
    П5["<b>П5</b><br/>Д3 ∧ Ф7"]
    Д5["<b>Д5</b><br/>Управление<br/>файловой<br/>системой"]
    
    Ф8["<b>Ф8</b><br/>Обработчики<br/>прерываний<br/>активны"]
    П6["<b>П6</b><br/>Д2 ∧ Ф8"]
    Д6["<b>Д6</b><br/>Обработка<br/>прерываний"]
    
    Ф9["<b>Ф9</b><br/>Очередь<br/>процессов<br/>готовности"]
    П7["<b>П7</b><br/>Ф9 ∧ Д4 ∧ Д6"]
    Д7["<b>Д7</b><br/>Планирование<br/>процессов"]
    
    П8["<b>П8</b><br/>Д3 ∧ Д4 ∧ Д5<br/>∧ Д6 ∧ Д7"]
    Д18["<b>Д18</b><br/>ОС функционирует<br/>корректно"]
    
    Ф1 --> П1
    Ф2 --> П1
    П1 --> Д1
    
    Д1 --> П2
    Ф3 --> П2
    П2 --> Д2
    
    Д2 --> П3
    Ф4 --> П3
    П3 --> Д3
    
    Д2 --> П4
    Ф6 --> П4
    П4 --> Д4
    
    Д3 --> П5
    Ф7 --> П5
    П5 --> Д5
    
    Д2 --> П6
    Ф8 --> П6
    П6 --> Д6
    
    Ф9 --> П7
    Д4 --> П7
    Д6 --> П7
    П7 --> Д7
    
    Д3 --> П8
    Д4 --> П8
    Д5 --> П8
    Д6 --> П8
    Д7 --> П8
    П8 --> Д18
    
    style Д18 fill:#90EE90
    style Д1 fill:#87CEEB
    style Д2 fill:#87CEEB
    style Д3 fill:#87CEEB
    style Д4 fill:#87CEEB
    style Д5 fill:#87CEEB
    style Д6 fill:#87CEEB
    style Д7 fill:#87CEEB